# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mdt0fArTMOjLFyr2BKjLxDZ5NUfqXU5D
"""

from IPython.display import HTML

html_content = """
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NARAVA | Ambiente · Seguridad · Salud</title>
    <!-- Fuentes de alto impacto similares a la referencia -->
    <link href="https://fonts.googleapis.com/css2?family=Syncopate:wght@400;700&family=Inter:wght@300;400;600;800&display=swap" rel="stylesheet">
    <style>
        :root {
            --primary: #2D5A27; /* Verde Institucional Narava */
            --accent: #8BC34A; /* Verde Brillante Acuático */
            --dark-bg: #0A0A0A; /* Negro Profundo (estilo Kings) */
            --surface: #141414;
            --white: #FFFFFF;
            --gray: #A0A0A0;
            --transition: all 0.5s cubic-bezier(0.23, 1, 0.32, 1);
        }

        * { margin: 0; padding: 0; box-sizing: border-box; }
        html { scroll-behavior: smooth; }
        body {
            font-family: 'Inter', sans-serif;
            background-color: var(--dark-bg);
            color: var(--white);
            line-height: 1.6;
            overflow-x: hidden;
        }

        /* --- NAVEGACIÓN ESTILO PREMIUM --- */
        header {
            position: fixed;
            top: 0;
            width: 100%;
            padding: 25px 5%;
            z-index: 2000;
            display: flex;
            justify-content: space-between;
            align-items: center;
            background: linear-gradient(to bottom, rgba(0,0,0,0.8), transparent);
            transition: var(--transition);
        }

        header.scrolled {
            padding: 15px 5%;
            background: rgba(10, 10, 10, 0.95);
            backdrop-filter: blur(10px);
            border-bottom: 1px solid rgba(255,255,255,0.1);
        }

        .logo-group {
            display: flex;
            align-items: center;
            gap: 15px;
            text-decoration: none;
        }

        .logo-svg {
            width: 45px;
            height: 45px;
            filter: drop-shadow(0 0 10px rgba(139, 195, 74, 0.3));
        }

        .logo-name {
            font-family: 'Syncopate', sans-serif;
            font-weight: 700;
            font-size: 1.4rem;
            letter-spacing: 3px;
            color: var(--white);
        }

        .nav-menu {
            display: flex;
            list-style: none;
            gap: 40px;
        }

        .nav-menu a {
            text-decoration: none;
            color: var(--white);
            font-size: 0.75rem;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 2px;
            opacity: 0.6;
            transition: var(--transition);
        }

        .nav-menu a:hover { opacity: 1; color: var(--accent); }

        /* --- HERO SECTION --- */
        .hero {
            height: 100vh;
            display: flex;
            align-items: center;
            padding: 0 10%;
            position: relative;
            background: radial-gradient(circle at 80% 20%, rgba(45, 90, 39, 0.15) 0%, transparent 50%),
                        linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.8)),
                        url('https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=2000') center/cover;
        }

        .hero-content {
            max-width: 900px;
            z-index: 10;
        }

        .hero-label {
            display: block;
            font-family: 'Syncopate', sans-serif;
            color: var(--accent);
            font-size: 0.9rem;
            margin-bottom: 20px;
            letter-spacing: 5px;
            text-transform: uppercase;
        }

        .hero h1 {
            font-family: 'Syncopate', sans-serif;
            font-size: clamp(2.5rem, 8vw, 5rem);
            font-weight: 700;
            line-height: 1;
            margin-bottom: 30px;
            text-transform: uppercase;
        }

        .hero-btn {
            display: inline-block;
            background: var(--white);
            color: var(--dark-bg);
            padding: 20px 45px;
            text-decoration: none;
            font-weight: 800;
            text-transform: uppercase;
            letter-spacing: 2px;
            font-size: 0.8rem;
            transition: var(--transition);
            border: 2px solid var(--white);
        }

        .hero-btn:hover {
            background: transparent;
            color: var(--white);
        }

        /* --- SECCIONES COMUNES --- */
        section { padding: 120px 10%; }

        .section-tag {
            color: var(--accent);
            font-family: 'Syncopate', sans-serif;
            font-size: 0.7rem;
            letter-spacing: 4px;
            margin-bottom: 15px;
            display: block;
        }

        .section-title {
            font-family: 'Syncopate', sans-serif;
            font-size: clamp(1.8rem, 4vw, 3rem);
            margin-bottom: 60px;
            text-transform: uppercase;
        }

        /* --- EMPRESA --- */
        .about-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 100px;
            align-items: center;
        }

        .about-text p {
            font-size: 1.1rem;
            color: var(--gray);
            margin-bottom: 30px;
        }

        .stats-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
        }

        .stat-card {
            background: var(--surface);
            padding: 40px;
            border-left: 4px solid var(--primary);
        }

        .stat-card h4 {
            color: var(--accent);
            margin-bottom: 10px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        /* --- SERVICIOS --- */
        .services { background-color: #0F0F0F; }

        .services-list {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            gap: 1px;
            background: rgba(255,255,255,0.1);
            border: 1px solid rgba(255,255,255,0.1);
        }

        .service-card {
            background: var(--dark-bg);
            padding: 60px 40px;
            transition: var(--transition);
            cursor: pointer;
            height: 100%;
        }

        .service-card:hover {
            background: var(--primary);
        }

        .service-card span {
            font-size: 0.8rem;
            color: var(--accent);
            margin-bottom: 20px;
            display: block;
        }

        .service-card h3 {
            font-family: 'Syncopate', sans-serif;
            font-size: 1.1rem;
            margin-bottom: 15px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        /* --- CONTACTO --- */
        .contact-container {
            display: grid;
            grid-template-columns: 0.8fr 1.2fr;
            gap: 80px;
        }

        .contact-form {
            display: grid;
            gap: 25px;
        }

        .form-group input, .form-group textarea {
            width: 100%;
            background: transparent;
            border: none;
            border-bottom: 2px solid rgba(255,255,255,0.1);
            padding: 15px 0;
            color: var(--white);
            font-family: inherit;
            font-size: 1rem;
            outline: none;
            transition: var(--transition);
        }

        .form-group input:focus, .form-group textarea:focus {
            border-bottom-color: var(--accent);
        }

        .submit-btn {
            background: var(--accent);
            color: var(--dark-bg);
            border: none;
            padding: 20px;
            font-weight: 800;
            text-transform: uppercase;
            letter-spacing: 2px;
            cursor: pointer;
            transition: var(--transition);
        }

        .submit-btn:hover {
            background: var(--white);
            transform: scale(1.02);
        }

        /* --- FOOTER --- */
        footer {
            padding: 80px 10%;
            border-top: 1px solid rgba(255,255,255,0.05);
            text-align: center;
        }

        .footer-logo {
            font-family: 'Syncopate', sans-serif;
            font-size: 2rem;
            color: var(--white);
            margin-bottom: 20px;
            display: block;
        }

        .social-links {
            margin-top: 30px;
            display: flex;
            justify-content: center;
            gap: 30px;
        }

        .social-links a { color: var(--gray); text-decoration: none; font-size: 0.8rem; letter-spacing: 2px; }
        .social-links a:hover { color: var(--white); }

        /* --- RESPONSIVE --- */
        @media (max-width: 992px) {
            .about-grid, .contact-container { grid-template-columns: 1fr; gap: 50px; }
            .hero { padding-top: 100px; text-align: center; }
            .nav-menu { display: none; }
        }
    </style>
</head>
<body>

    <header id="mainHeader">
        <a href="#" class="logo-group">
            <svg class="logo-svg" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
                <rect width="100" height="100" rx="20" fill="#2D5A27"/>
                <path d="M30 75V25L50 50L70 25V75" stroke="white" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M78 20C88 30 88 50 78 60" stroke="#8BC34A" stroke-width="4" stroke-linecap="round"/>
            </svg>
            <span class="logo-name">NARAVA</span>
        </a>
        <ul class="nav-menu">
            <li><a href="#inicio">Inicio</a></li>
            <li><a href="#nosotros">Empresa</a></li>
            <li><a href="#servicios">Servicios</a></li>
            <li><a href="#contacto">Contacto</a></li>
        </ul>
    </header>

    <section id="inicio" class="hero">
        <div class="hero-content">
            <span class="hero-label">Ambiente · SST</span>
            <h1>Sostenibilidad con impacto real</h1>
            <p>Brindamos soluciones integrales en gestión ambiental y seguridad industrial en Medellín para empresas comprometidas con la excelencia.</p>
            <a href="#servicios" class="hero-btn">Nuestras Soluciones</a>
        </div>
    </section>

    <section id="nosotros">
        <span class="section-tag">Perfil Empresarial</span>
        <h2 class="section-title">Sobre Narava</h2>
        <div class="about-grid">
            <div class="about-text">
                <p>Narava es una organización especializada en consultoría estratégica para el cumplimiento normativo ambiental y de seguridad industrial. Ubicados en Medellín, integramos conocimiento técnico avanzado para acompañar proyectos de infraestructura y sector empresarial.</p>
                <div class="stats-grid">
                    <div class="stat-card">
                        <h4>Misión</h4>
                        <p style="font-size: 0.9rem;">Impulsar la sostenibilidad y el bienestar laboral mediante soluciones técnicas de alta calidad.</p>
                    </div>
                    <div class="stat-card">
                        <h4>Visión</h4>
                        <p style="font-size: 0.9rem;">Ser el aliado estratégico líder en servicios ambientales y de seguridad en Colombia.</p>
                    </div>
                </div>
            </div>
            <div style="position: relative;">
                <img src="https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&q=80&w=1000" alt="Consultoría Ambiental Narava" style="width: 100%; filter: grayscale(50%) contrast(1.2);">
                <div style="position: absolute; bottom: -20px; right: -20px; background: var(--accent); width: 100px; height: 100px; z-index: -1;"></div>
            </div>
        </div>
    </section>

    <section id="servicios" class="services">
        <span class="section-tag">Portafolio Técnico</span>
        <h2 class="section-title">Servicios Especializados</h2>
        <div class="services-list">
            <div class="service-card">
                <span>01</span>
                <h3>Gestión Ambiental Integral</h3>
                <p style="color: var(--gray); font-size: 0.9rem;">Asesoría estratégica en trámites de licencias, permisos de vertimientos y cumplimiento de normatividad vigente.</p>
            </div>
            <div class="service-card">
                <span>02</span>
                <h3>Huella de Carbono</h3>
                <p style="color: var(--gray); font-size: 0.9rem;">Medición técnica de emisiones de gases de efecto invernadero y diseño de planes de mitigación y compensación.</p>
            </div>
            <div class="service-card">
                <span>03</span>
                <h3>Sistemas SG-SST</h3>
                <p style="color: var(--gray); font-size: 0.9rem;">Implementación y auditoría de Sistemas de Gestión de Seguridad y Salud en el Trabajo bajo estándares nacionales.</p>
            </div>
            <div class="service-card">
                <span>04</span>
                <h3>Gestión de Residuos</h3>
                <p style="color: var(--gray); font-size: 0.9rem;">Planes de manejo integral de residuos sólidos (PMIRS) y residuos peligrosos con enfoque en economía circular.</p>
            </div>
        </div>
    </section>

    <section id="contacto">
        <span class="section-tag">Contacto Directo</span>
        <h2 class="section-title">Hablemos de su proyecto</h2>
        <div class="contact-container">
            <div>
                <p style="font-size: 1.4rem; font-weight: 300; margin-bottom: 40px;">Contamos con un equipo de especialistas listo para optimizar sus procesos ambientales y de seguridad.</p>
                <div style="margin-bottom: 20px;">
                    <span style="color: var(--accent); display: block; font-size: 0.8rem; letter-spacing: 2px;">CANAL OFICIAL</span>
                    <p>gerencianarava@gmail.com</p>
                </div>
                <div>
                    <span style="color: var(--accent); display: block; font-size: 0.8rem; letter-spacing: 2px;">SEDE CENTRAL</span>
                    <p>Medellín, Antioquia</p>
                </div>
            </div>
            <form class="contact-form">
                <div class="form-group">
                    <input type="text" placeholder="NOMBRE / EMPRESA" required>
                </div>
                <div class="form-group">
                    <input type="email" placeholder="CORREO ELECTRÓNICO" required>
                </div>
                <div class="form-group">
                    <textarea rows="4" placeholder="DESCRIBA SU REQUERIMIENTO TÉCNICO"></textarea>
                </div>
                <button type="submit" class="submit-btn">Solicitar Asesoría</button>
            </form>
        </div>
    </section>

    <footer>
        <span class="footer-logo">NARAVA</span>
        <p style="color: var(--gray); font-size: 0.8rem; letter-spacing: 1px;">AMBIENTE · SEGURIDAD · SALUD EN EL TRABAJO</p>
        <div class="social-links">
            <a href="https://www.linkedin.com/company/naravaservicios" target="_blank">LINKEDIN</a>
            <a href="#">CONSULTORÍA</a>
            <a href="#">PROYECTOS</a>
        </div>
        <p style="margin-top: 50px; font-size: 0.7rem; opacity: 0.3;">© 2026 NARAVA S.A.S. MEDELLÍN, COLOMBIA.</p>
    </footer>

    <script>
        // Efecto de scroll en el header
        window.addEventListener('scroll', () => {
            const header = document.getElementById('mainHeader');
            if (window.scrollY > 50) {
                header.classList.add('scrolled');
            } else {
                header.classList.remove('scrolled');
            }
        });

        // Animación de entrada
        const observerOptions = { threshold: 0.1 };
        const observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.style.opacity = '1';
                    entry.target.style.transform = 'translateY(0)';
                }
            });
        }, observerOptions);

        document.querySelectorAll('.service-card, .stat-card').forEach(el => {
            el.style.opacity = '0';
            el.style.transform = 'translateY(30px)';
            el.style.transition = 'all 0.8s ease-out';
            observer.observe(el);
        });
    </script>
</body>
</html>
"""

HTML(html_content)